# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syntax_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(960, 540)
        dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("help/system.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        dialog.setModal(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grammar_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.grammar_label.setFont(font)
        self.grammar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.grammar_label.setObjectName("grammar_label")
        self.verticalLayout.addWidget(self.grammar_label)
        self.grammar_table = QtWidgets.QTableWidget(self.frame)
        self.grammar_table.setObjectName("grammar_table")
        self.grammar_table.setColumnCount(2)
        self.grammar_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.grammar_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grammar_table.setHorizontalHeaderItem(1, item)
        self.grammar_table.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.grammar_table)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lst_label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lst_label.setFont(font)
        self.lst_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lst_label.setObjectName("lst_label")
        self.verticalLayout_2.addWidget(self.lst_label)
        self.lst_table = QtWidgets.QTableWidget(self.frame_2)
        self.lst_table.setObjectName("lst_table")
        self.lst_table.setColumnCount(3)
        self.lst_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lst_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lst_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lst_table.setHorizontalHeaderItem(2, item)
        self.lst_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.lst_table)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.predict_label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.predict_label.setFont(font)
        self.predict_label.setAlignment(QtCore.Qt.AlignCenter)
        self.predict_label.setObjectName("predict_label")
        self.verticalLayout_3.addWidget(self.predict_label)
        self.predict_table = QtWidgets.QTableWidget(self.frame_3)
        self.predict_table.setObjectName("predict_table")
        self.predict_table.setColumnCount(0)
        self.predict_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.predict_table)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "语法信息"))
        self.grammar_label.setText(_translate("dialog", "文法及Select集"))
        item = self.grammar_table.horizontalHeaderItem(0)
        item.setText(_translate("dialog", "产生式"))
        item = self.grammar_table.horizontalHeaderItem(1)
        item.setText(_translate("dialog", "Select集"))
        self.lst_label.setText(_translate("dialog", "First集与Follow集"))
        item = self.lst_table.horizontalHeaderItem(0)
        item.setText(_translate("dialog", "非终结符"))
        item = self.lst_table.horizontalHeaderItem(1)
        item.setText(_translate("dialog", "First集"))
        item = self.lst_table.horizontalHeaderItem(2)
        item.setText(_translate("dialog", "Follow集"))
        self.predict_label.setText(_translate("dialog", "预测分析表"))
