# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'semantic_res.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 540)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.symbol_tbl = QtWidgets.QTableWidget(self.frame)
        self.symbol_tbl.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.symbol_tbl.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.symbol_tbl.setObjectName("symbol_tbl")
        self.symbol_tbl.setColumnCount(4)
        self.symbol_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.symbol_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.symbol_tbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.symbol_tbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.symbol_tbl.setHorizontalHeaderItem(3, item)
        self.symbol_tbl.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.symbol_tbl)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.code_tbl = QtWidgets.QTableWidget(self.frame_2)
        self.code_tbl.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.code_tbl.setObjectName("code_tbl")
        self.code_tbl.setColumnCount(2)
        self.code_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.code_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.code_tbl.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.code_tbl)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.err_tbl = QtWidgets.QTableWidget(self.frame_3)
        self.err_tbl.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.err_tbl.setObjectName("err_tbl")
        self.err_tbl.setColumnCount(3)
        self.err_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.err_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.err_tbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.err_tbl.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.err_tbl)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "语义分析"))
        self.label_2.setText(_translate("Dialog", "符号表"))
        item = self.symbol_tbl.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "序号"))
        item = self.symbol_tbl.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "字符串"))
        item = self.symbol_tbl.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "类型"))
        item = self.symbol_tbl.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "偏移或跳转"))
        self.label.setText(_translate("Dialog", "三地址指令和四元式表示"))
        item = self.code_tbl.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "三地址"))
        item = self.code_tbl.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "四元式"))
        self.label_3.setText(_translate("Dialog", "错误信息"))
        item = self.err_tbl.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "行号"))
        item = self.err_tbl.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "错误"))
        item = self.err_tbl.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "信息"))
