# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syntax_res.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 540)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../help/system.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 15, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.syntax_table = QtWidgets.QTableWidget(self.frame)
        self.syntax_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.syntax_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.syntax_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.syntax_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.syntax_table.setGridStyle(QtCore.Qt.SolidLine)
        self.syntax_table.setObjectName("syntax_table")
        self.syntax_table.setColumnCount(3)
        self.syntax_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.syntax_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.syntax_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.syntax_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.syntax_table)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.error_table = QtWidgets.QTableWidget(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.error_table.setFont(font)
        self.error_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.error_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.error_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.error_table.setObjectName("error_table")
        self.error_table.setColumnCount(3)
        self.error_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.error_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.error_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.error_table.setHorizontalHeaderItem(2, item)
        self.error_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.error_table)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.syntax_tree = QtWidgets.QTreeWidget(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.syntax_tree.setFont(font)
        self.syntax_tree.setAlternatingRowColors(False)
        self.syntax_tree.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.syntax_tree.setObjectName("syntax_tree")
        self.syntax_tree.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.syntax_tree)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "语法分析"))
        self.label.setText(_translate("Dialog", "分析过程"))
        item = self.syntax_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "符号栈"))
        item = self.syntax_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "输入栈"))
        item = self.syntax_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "操作"))
        self.label_2.setText(_translate("Dialog", "错误"))
        item = self.error_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "行号"))
        item = self.error_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "错误"))
        item = self.error_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "信息"))
        self.label_3.setText(_translate("Dialog", "分析树"))
